version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest

    steps:
      # Checkout code
      - checkout

      - run: echo "hi" > hi.txt

workflows:
  version: 2
  build:
    jobs:
      - build

